name: basketball_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  gap: ^2.0.0
  go_router: ^7.0.0
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
